### ISSUE TITLE
Snafu cannot be used with color_backtrace::print_backtrace

### ISSUE THREAD

**Issue by ArekPiekarz** [shepmaster/snafu#118]
[color-backtrace](https://crates.io/crates/color-backtrace) is a crate for printing colored, expanded backtraces with source context. It offers, among others, a function [print_backtrace](https://docs.rs/color-backtrace/0.2.2/color_backtrace/fn.print_backtrace.html), which takes backtrace::Backtrace as an argument. I wanted to use it with Snafu, however this crate's [backtrace shim](https://docs.rs/snafu/0.4.1/src/snafu/backtrace_shim.rs.html) hides the required type as private.

Would it be possible to somehow expose the inner type to allow usage with color-backtrace?

**Comment by shepmaster** [comment]
I don't want to let people know that it's a `backtrace::Backtrace` by default. Ideally, at some point in the future, the standard library will gain its own `Backtrace` type; when that happens I want to be able to transparently transition for those who use that version.

In the meantime, I don't see a reason we shouldn't add a new feature flag that, when enabled, adds an `AsRef<backtrace::Backtrace>` implementation.

**Comment by shepmaster** [comment]
General guidelines for implementation:

1. Add a new feature flag (thoughts: `expose-backtrace`, `backtrace-crate`, `as-backtrace`)
1. When that flag is present, implement [`AsRef`](https://doc.rust-lang.org/std/convert/trait.AsRef.html) for `backtrace::Backtrace` on `snafu::Backtrace`.

**Comment by shepmaster** [comment]
@ArekPiekarz would your use case still be met if `snafu::Backtrace` were just a type alias for `backtrace::Backtrace`? This would mean that we wouldn't implement `Display` for the backtrace anymore. As I understand your case, you get the `snafu::Backtrace`, then `backtrace::Backtrace`, and never look back at the SNAFU type; is that right?

**Comment by ArekPiekarz** [comment]
I only need backtrace::Backtrace object to pass it to color_backtrace::print_backtrace, which in turn uses backtrace's frames() - https://docs.rs/color-backtrace/0.2.3/src/color_backtrace/lib.rs.html#501. In my case lack of Display wouldn't be a problem.
