### ISSUE TITLE
Improve accuracy of spans in attribute misuse/duplication errors

### ISSUE THREAD

**Issue by tjkirch** [shepmaster/snafu#126]
In #109, new error messages were added to help explain misuse and duplication of snafu attributes.  The source spans used for the error messages refer to the name of the struct, enum, variant, or field on which the attribute was placed.  This is helpful for finding the issue, but isn't the most accurate - in some cases it would be better to point to the attribute itself, rather than the element it was placed on.

**Comment by tjkirch** [comment]
I'm working on this one and making good progress.  There are a couple corner cases I'm trying to catch, and some of the spans for `syn::Attribute`s seem to reference just the `#` character instead of the whole `#[...]`, but even so there's already a big improvement.  The worst case is that I'll start with a WIP PR to ask for help on some specifics.

**Comment by shepmaster** [comment]
> some of the spans for `syn::Attribute`s seem to reference just the `#` character instead of the whole `#[...]`

You'll want to check on [`Error::new_spanned`](https://docs.rs/syn/0.15.39/syn/struct.Error.html#method.new_spanned). It provides better spans in those cases.

**Comment by tjkirch** [comment]
> You'll want to check on [`Error::new_spanned`](https://docs.rs/syn/0.15.39/syn/struct.Error.html#method.new_spanned). It provides better spans in those cases.

It took a bit of doing to get `TokenStream`s for `new_spanned` (ownership issues) but that does indeed fix the issue!  With this change it even points out individual attributes instead of the entire line, which I imagine would help if multiple attributes are specified in one `#[snafu(...)]`.

Still working on the corner cases, which result in ugly things like errors pointing to a field and all of its attributes, instead of the one relevant attribute.

**Comment by shepmaster** [comment]
> get `TokenStream`s for `new_spanned` (ownership issues)

I think it's fine to create `Box<ToTokens>` trait objects here, if that makes it easier.
