### ISSUE TITLE
Add a contributor's guide

### ISSUE THREAD

**Issue by tjkirch** [shepmaster/snafu#127]
I think it'd be a good idea to have a `CONTRIBUTING.md` in the repo to help guide new contributors.  It can make a project seem a bit more approachable, and can save time in pull requests.

Background on contributor's guides on GitHub: https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

I picked up a few specific tips from #109 that could serve as starting material; something like these could be combined with more general procedural tips and some encouragement for newcomers.

Communication tips:
* Open an issue for discussion before writing any non-trivial changes - often the author or other contributors can help shape an even better idea.  Or maybe someone is already working on it!
* Even if you're making a breaking change, don't worry about updating the version number or changelog -- they're done together before a release -- but feel free to suggest wording you like in the pull request.
* We value correctness and clarity in the code, API, and docs, and it's worth putting in the time for thorough review in issues and pull requests.
* Don't try to fix the world in a single issue or pull request.  Even small issues can sprout many good ideas, and feel free to split those into new issues.

Testing tips:
* We maintain compatibility with older versions of Rust, and this is enforced through compatibility testing that runs automatically when you create or update a pull request.  You can run these earlier, locally, by running `cargo test` in one of the directories under `compatibility-tests/` - the `rust-toolchain` files there will cause the right version of Rust to be used, assuming you use rustup.  Be aware that you may need to install specific versions of dependencies, as described in `.cirrus.yml` at the root of the repo.
* If you're adding a new compile-time error, add a sample under `compatibility-tests/compile-fail/tests/ui/` to be sure it fails in the way you expect.
* If you're adding a new feature, add a unit test for it in a file that sounds relevant under `tests/` - unit tests are not written in the library files.

General tips:
* Before 1.0, breaking changes are OK if they're adding value - we can update the minor version as needed.
* The user's guide is a valuable resource and worth the time to keep up to date when adding or changing the library.

**Comment by shepmaster** [comment]
Honestly, this all seems like a great start; I don't see any reason to not open a PR with it; I might do a little style tweaking with it, but that's easy to do in the PR.
