### ISSUE TITLE
snafu::futures::try_future::Context is not awaitable

### ISSUE THREAD

**Issue by pluth** [shepmaster/snafu#134]
I'm trying to use snafu in an async/await project and I am running into the following Issue:

Every Future (std) implements TryFuture when it returns Result<_, _> due to the blanket implementation in https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.17/futures/future/trait.TryFuture.html#implementors. However, the opposite does not seems to be true, i.e. a TryFuture does not automatically implement Future.

As snafu::futures::try_future::Context implements TryFuture directly, it does not implement Future and is therefore not awaitable. Would you consider a change to Context so that it implements Future<Output = Result<..>> instead? It would keep the TryFuture implementation through the blanket implementation above.

I've modified the example of the [context](https://docs.rs/snafu/0.4.3/snafu/futures/trait.TryFutureExt.html#tymethod.context) method to demonstrate:

```rust
#![feature(async_await)]

use futures::future::TryFuture;
use snafu::{futures::TryFutureExt, Snafu};

#[derive(Debug, Snafu)]
enum Error {
    Authenticating {
        user_name: String,
        user_id: i32,
    },
}

async fn example() -> Result<i32, Error> {
    another_function().context(Authenticating {
        user_name: "admin",
        user_id: 42_i32,
    }).await // Error here
   // the trait bound `snafu::futures::try_future::Context<impl core::future::future::Future, 
   // &Authenticating<&str, i32>, Error>: core::future::future::Future` is not satisfied
   // required by `std::future::poll_with_tls_context`rustc(E0277)
}


async fn another_function() -> Result<i32, ()> {
    unimplemented!();
}

```

**Comment by shepmaster** [comment]
> Would you consider a change to Context so that it implements Future<Output = Result<..>> instead

Certainly; so long as it continues to pass what tests we have, ideally adding a new test for the functionality that is currently lacking.

TBH, I wasn't sure how people would want to call it. I'd have expected that most usages would be `future.await.context(...)` (using `ResultExt`) instead of `future.context(...).await` (using `TryFutureExt`);

Any change would also want to apply to the `Stream` combinators as well.

**Comment by pluth** [comment]
> I'd have expected that most usages would be future.await.context(...) (using ResultExt)

Yes, that's what I'm doing now. I just tried TryFutureExt first, mostly because I thought it would look better with await at the end.

I will create a PR

**Comment by shepmaster** [comment]
> I thought it would look better with await at the end.

And I think we should definitely support both; sorry for not testing both ways and causing you trouble!

> I will create a PR

Wonderful!

**Comment by pluth** [comment]
> sorry for not testing both ways and causing you trouble!
No worries, opened #136
