### ISSUE TITLE
Multiple SNAFU attributes are not supported in one attribute

### ISSUE THREAD

**Issue by shepmaster** [shepmaster/snafu#135]
It is intended that we can say `#[snafu(a, b, c)]`, but it doesn't appear to work:

```rust
#[derive(Debug, Snafu)]
pub(crate) enum Error {
    #[snafu(visibility(pub(crate)), display("Moo"))]
    Alpha,
}
```

```
error: unexpected token
 --> tests/multi.rs:8:39
  |
8 |         #[snafu(visibility(pub(crate)), display("Moo"))]
  |                                       ^
```

**Comment by shepmaster** [comment]
I think the problem is that this parenthesis handling needs to be moved out of `SnafuAttribute` and  up into `SnafuAttributeBody`

https://github.com/shepmaster/snafu/blob/31ac98aa3b4aff990fc8c5f416489f485cebf8cb/snafu-derive/src/lib.rs#L918-L920

**Comment by tjkirch** [comment]
Thanks for the pointer :)  Created PR #137.  I was hoping this would help with the parentheses issue in #133, which it didn't directly, but it did help me learn about syn parsing and gives me a couple more ideas to try for the other issue.

**Comment by shepmaster** [comment]
> I was hoping this would help with the parentheses issue

Yeah, I expected it too as well!
