### ISSUE TITLE
Decide on Rust 1.18 vs 1.31 requirement

### ISSUE THREAD

**Issue by shepmaster** [shepmaster/snafu#154]
syn/quote/proc-macro2 just [updated to version 1.0](https://github.com/dtolnay/syn/releases/tag/1.0.0) and now require Rust 1.31+. Upgrading would break *our* version requirements. 

I chose the current 1.18 as basically "how early could we go without being terrible". My idea was to support as many Rust versions as possible in order to allow a broad range of projects to use SNAFU. 

It may not be the case that anyone *cares* about these older versions, though. Rust 1.31 is nearly 9 months old, and is 5 stable releases behind. I have a gut feeling that most people track stable or a few stable versions behind. 1.31 also has the notable benefit of being the release of Rust 2018 and NLL, things that people hotly anticipated and wanted.

As a user of SNAFU, I'd appreciate it if you'd vote on **one of** the following comments to provide feedback on what Rust versions we should support.

**Comment by shepmaster** [comment]
Please add a 👍 to **this** comment if you'd like SNAFU to continue supporting Rust 1.18.

**Comment by shepmaster** [comment]
Please add a 👍 to **this** comment if you'd be OK with SNAFU only supporting Rust 1.31+.

**Comment by BurntSushi** [comment]
For crates I maintain that a lot of people depend on, I try to be fairly conservative, and my rough ballpark heuristic is "lag about a year behind latest stable." I think 9 months is just fine personally.

**Comment by Dylan-DPC** [comment]
Faced with a similar situation earlier, I often solve it by asking the question "is there any language feature from those versions (1.18 to 1.30) that you depend on? if no, bump + major release

**Comment by shepmaster** [comment]
@Dylan-DPC I've read your comment a few times over the last few hours, but I'm still confused. I'll try restating this specific problem with the hopes that I've communicated something poorly.

SNAFU has a dependency on syn/quote/proc-macro2 (which I'll shorten to just "syn" for the rest of this comment). Those dependencies have recently released version 1.0, and chosen to only guarantee compatibility with Rust 1.31 and *do not compile* on Rust 1.18. The previous versions had compatibility back to Rust 1.15, but SNAFU itself required Rust 1.18.

### SNAFU does nothing and stays on the current version of syn

Pro:
- supports Rust 1.18+
- more people/projects can use SNAFU

Con:
- annoyance to the people that will have to compile multiple versions of syn
- *maybe* cause issues with parsing future Rust syntax 

### SNAFU upgrades to syn 1.0

Pro:
- only build one version of syn, once most crates are updated
- our code can upgrade to Rust 2018 and be simplified

Con:
- Can no longer use SNAFU with versions of Rust before 1.31. 

### Implementation details

I'm in the camp that believes that bumping the minimum Rust version corresponds to a semver-incompatible version change. If we upgraded to syn 1.0 *today*, then our minimum Rust version is changed, and we would need to release SNAFU 0.5 (since we haven't yet hit 1.0). That version number bump is dependent on when/if we do such a change, of course.

---

> is there any language feature from those versions (1.18 to 1.30) that you depend on? 

No, there are no language features between Rust 1.18 and 1.30 that SNAFU requires.

> if no, bump + major release

I don't follow why the answer "no" would mean this. What would the answer "yes" mean?

**Comment by shepmaster** [comment]
Thanks everyone! Since there are no dissenting opinions, I see no reason not to upgrade.
