### ISSUE TITLE
Is SNAFU compatible with macOS / apple targets?

### ISSUE THREAD

**Issue by erazor-de** [shepmaster/snafu#162]
I'm relatively new to Rust and if I decide about using a crate I tend to have a look at the supported platforms to not limit a project should need be for another target than Linux.
For this crate the [documentation](https://docs.rs/snafu/0.4.4/snafu/) only lists i686-pc-windows-msvc, x86_64-pc-windows-msvc and x86_64-unknown-linux-gnu as platforms. Why no apple target? Is this a "won't work" or a "not tested but expected to work" issue?

**Comment by shepmaster** [comment]
I expect that SNAFU will work with **every** possible Rust target. It is the intention that there's zero platform-specific code.

> For this crate the [documentation](https://docs.rs/snafu/0.4.4/snafu/) only lists

I honestly don't know what platforms docs.rs chooses to build on. Before this issue, I thought it was just on Linux and you could opt in to Windows if your crate needed it. My *guess* is that it builds on a set of platforms and that when I uploaded the last few versions of SNAFU, the other builders were out of commission. I'll see if I can find the build logs though.
