### ISSUE TITLE
Upgrade syn/quote/proc-macro2 to 1.0

### ISSUE THREAD

**Issue by tjkirch** [shepmaster/snafu#164]
Assuming #154 decides to bump SNAFU's Rust requirement to 1.31, we'll be able to upgrade our syn, quote, and proc-macro2 dependencies to 1.0, which also require Rust 1.31.

https://github.com/dtolnay/syn/releases/tag/1.0.0

Some potential benefits mentioned in #145: "making more use of the powers given by the new versions, maybe mostly in quote. For example all of the repetition things mentioned are issues we encountered."

Potentially related, also from #145: "I've had a mild sense that snafu-derive's lib.rs is simply too big at this point and could benefit from some reorganization. Perhaps reviewing the code during such reorganization would be a good time."

**Comment by tjkirch** [comment]
> making more use of the powers given by the new versions, maybe mostly in quote. For example all of the repetition things mentioned are issues we encountered.

I looked through the [quote 1.0 release notes](https://github.com/dtolnay/quote/releases/tag/1.0.0), addressed what I could find, and pushed a couple more commits to https://github.com/tjkirch/snafu/commits/upgrade-minimum to make use of the improvements.

I initially thought that https://github.com/shepmaster/snafu/blob/master/snafu-derive/src/lib.rs#L1275 was a case of "Reusing values across repetitions" from the release notes, because changing `f.name.clone` to `&f.name` worked fine, but it turns out that worked with pre-1.0 quote too.

@shepmaster: I didn't find as much improvement as I expected to, which makes me think I missed some difficulties you had in the code.  If you expect more than those two small improvements, I'd be interested in any pointers you could give!

@shepmaster: Also, if you have a moment for a quick look at the commits in that branch, I'd be interested in anything else you'd like to see covered in a PR, or if it seems ready for a PR now.  You'll see I didn't touch `lib.rs`, which you mentioned as a possible change to include - I wasn't sure how it related to the other upgrades.

**Comment by shepmaster** [comment]
I think we might as well do this, so let's open up a PR to discuss specific changes. The two I know immediately are:

- I'd reorder the commits: Drop 1.18, Drop 1.30, Upgrade to 2018, upgrade crates, various cleanups
- Another cleanup is to replace `let foo: &Vec<_> = &blah.collect()` with `let foo: Vec<_> = blah.collect()`.

**Comment by tjkirch** [comment]
I just got back from a break, so I should be able to fix up what you suggested and get a PR out within a few days. :)

**Comment by tjkirch** [comment]
I made the requested changes and opened #177.
