### ISSUE TITLE
derive(Snafu) fails if you use it inside a crate that has another module named 'snafu'

### ISSUE THREAD

**Issue by crmckenzie** [shepmaster/snafu#165]
The full context is that we have some extensions we wrote on top of snafu that we put in a module named snafu. We can discriminate the module names fairly easily using `::snafu` to represent your crate and `crate::snafu` to represent our extensions. No problems there. However, the `derive(Snafu)` macro usage fails to compile and gives a message about `Snafu doesn't implement AsErrorSource()` or some such.

I suspect that this could be resolved by having the derive macro specify the global namespace before referencing snafu components internally. I've worked around it for the moment. If I get some time early next week I'll look at submitting a PR.

```rust
#[derive(Debug, ::snafu::Snafu)]
pub enum Test {
    One,
}
```

```
132 | #[derive(Debug, ::snafu::Snafu)]
    |                 ^^^^^^^^^^^^^^ no `AsErrorSource` in `snafu`
```

**Comment by shepmaster** [comment]
Sorry for the trouble!

Is your crate using Rust 2015 or 2018? (check in Cargo.toml for the `edition` setting)

**Comment by shepmaster** [comment]
It would also be create if you could create a minimal example that demonstrates the problem, including the imports, module definitions, and Cargo.toml. That way we can directly use that as a testcase and avoid any future regressions.
