### ISSUE TITLE
Snafu is Great

### ISSUE THREAD

**Issue by casey** [shepmaster/snafu#181]
Thank you so much for Snafu! It's exactly the way I like to handle errors. I've used it in three or four crates, and it's both more ergonomic  and readable than how I've handled errors before.

I actually posted a similar but more limited error handling pattern that I originally settled on to reddit, and the [first comment](https://www.reddit.com/r/rust/comments/d56vgt/simple_and_ergonomic_pattern_for_adding_context/f0k81bx/) pointed me towards Snafu, which is how I found out about it.

I would have written an email, but I couldn't find your address, so forgive the issue, which I'm going to go ahead and immediately close ^_^

**Comment by shepmaster** [comment]
Thanks! 

> I couldn't find your address

Opening an issue is fine (it lets everyone else see that at least one person besides myself loves SNAFU 😉). I often look at git commits for the user I'm interested in contacting, but I've also added my business email to the profile.
