### ISSUE TITLE
Finding error type

### ISSUE THREAD

**Issue by saiumesh535** [shepmaster/snafu#209]
Thanks for the great crate. I just included this in one of our projects. 

**Q:** Is there any way to figure out the error type.

Sample code as follows 

Thanks!

```rust
use snafu::{Snafu};

#[derive(Debug, Snafu)]
enum InnerError {
    #[snafu(display("User ID {} is invalid", user_id))]
    InvalidUser { user_id: i32 },
    #[snafu(display("User ID {} is locked", user_id))]
    UserLocked { user_id: i32 },
}

#[derive(Debug, Snafu)]
pub struct Error(InnerError);

fn validate_user(user_id: i32) -> Result<(), InnerError> {
    InvalidUser { user_id }.fail()
}

fn is_user_locked(user_id: i32) -> Result<(), InnerError> {
    UserLocked { user_id }.fail()
}

pub fn login(id: i32) -> Result<(), Error> {
    validate_user(id)?;
    is_user_locked(id)?;
    Ok(())
}

fn main() {
    match login(1) {
        Ok(_) => {
        },
        Err(e) => {
            // how to find error type, whether it is InvalidUser or UserLocked
            println!("{}", e);
        }
    }
}
```

**Comment by shepmaster** [comment]
> Is there any way to figure out the error type

I don't understand your question... The error types are whatever types you've made. In your example, there are two error types: `InnerError` and `Error`. Perhaps you can restate your question in a different way?

**Comment by saiumesh535** [comment]
I should have more clear. once we catch err, how to find error type, whether it is InvalidUser or UserLocked.
So based on error type we could some specific tasks. 

```rust
match login(1) {
        Ok(_) => {
        },
        Err(e) => {
            // how to find error type, whether it is InvalidUser or UserLocked
            println!("{}", e);
           
         // maybe something like this.
        if err.type == InnerError. InvalidUser {
            // do some specific task
        }

        }
    }
```

**Comment by shepmaster** [comment]
Gotcha. One of the design goals of SNAFU is that the error type itself is standard Rust code. Here, `Error` is a newtype around `InnerError` Which is an enum. This means you can use all the normal Rust pattern matching capabilities:

```rust

fn main() {
    match login(1) {
        Ok(_) => {}
        Err(e) => match e {
            Error(InnerError::InvalidUser { user_id }) => {}
            Error(InnerError::UserLocked { user_id }) => {}
        },
    }
}
```

Or any of a wide variety of existing Rust techniques. For example, the `Error` type is an opaque type, so callers of your API don’t see the internals. You may want to add public methods to it that your users can call.

**Comment by saiumesh535** [comment]
It worked, Thank you for this crate. Should I create PR add it to Docs ?
