### ISSUE TITLE
Use Snafu to convert NoneError

### ISSUE THREAD

**Issue by ethanabrooks** [shepmaster/snafu#213]
Given the existence of `snafu::NoneError`, I thought the following would be possible:

```rust
#![feature(try_trait)]
use snafu;
use snafu::OptionExt;
use snafu::Snafu;

#[derive(Debug, Snafu)]
pub enum MyError {
    #[snafu()]
    NoneError { source: snafu::NoneError },
}

fn main() -> Result<(), MyError> {
    None.context(NoneError {})?;
    Ok(())
}
```
I searched the documentation but didn't find anything besides this: https://docs.rs/snafu/0.6.2/snafu/struct.NoneError.html

Am I doing this wrong, or does this feature not exist?

**Comment by shepmaster** [comment]
There's no point to keeping the `None` source (as it would have no useful information). If you check the [options test](https://github.com/shepmaster/snafu/blob/0e18dbd730fcb0b6c207e0ae29246e32387d362d/tests/options.rs), your code would look like:

```rust
use snafu::{self, OptionExt, Snafu};

#[derive(Debug, Snafu)]
pub enum MyError {
    NoneError,
}

fn main() -> Result<(), MyError> {
    None.context(NoneError)?;
    Ok(())
}
```

**Comment by ethanabrooks** [comment]
That solved it. Great library. Thanks for your help.
