### ISSUE TITLE
Error handling for errors that do not implement `std::error::Error`

### ISSUE THREAD

**Issue by ethanabrooks** [shepmaster/snafu#214]
I need to handle an error that doesn't implement the `Error` trait (namely [`lcov::reader::Error`](https://docs.rs/lcov/0.5.0/lcov/reader/enum.Error.html)). I am currently using:
```rust
records.map_err(|_| {
    LcovReadError {
        string: lcov_string.clone(),
    }
    .into_error(snafu::NoneError)
})?;
```
where `records: Result<_, lcov::reader::Error>`.
My definition for `LcovReadError` is
```rust
#[derive(Debug, Snafu)]
#[snafu(visibility(pub))]
pub enum MyError {
    #[snafu(display("Unable to parse lcov string:\n{}", string))]
    LcovReadError { string: String },
}
```
Is this the most idiomatic implementation?

**Comment by shepmaster** [comment]
See also #103

**Comment by shepmaster** [comment]
See also #23

**Comment by shepmaster** [comment]
Your example code is fine, but a recent version of SNAFU did simplify this some. I think this would work:

```rust
records.map_err(|_| LcovReadError { string: &lcov_string }.build())?;
```
