### ISSUE TITLE
Enhance `ensure` macro to allow trailing commas

### ISSUE THREAD

**Issue by shepmaster** [shepmaster/snafu#243]

**Comment by Henning-K** [comment]
For clarification: Do you mean "trailing comma" as in (drawing on the example from the docs):
```rust
ensure!(user_id > 0, InvalidUser {user_id}, );
------------------------------------------^
```
Or that the part after the first comma can be missing, because that doesn't really make sense.

**Comment by shepmaster** [comment]
Sorry! I marked this notification as read without responding to it. Yes, the goal is to support

```rust
ensure!(
    some_long_condition,
    AnotherLongThing { more_long },
    // ---------------------------^
);
```
