### ISSUE TITLE
Non static error type chaining

### ISSUE THREAD

**Issue by Qwaz** [shepmaster/snafu#253]
Hello, I'm currently working on a project which uses an arena allocator. This setup makes almost all values and errors have `'arena` lifetime.

The problem is that every type that goes to `source` field should have `'static` lifetime because of the [requirement of the Error trait](https://doc.rust-lang.org/std/error/trait.Error.html#method.source). This restriction makes it impossible to use Snafu to chain my error types via `source` field.

If my understanding is correct, Snafu's mechanism for attaching context to hierarchical errors does not necessarily need `'static` lifetime. Is there a way to opt-out from automatic implementation of `Error` trait or make `source()` always return `None`, and use non static error types for error chaining?

**Comment by shepmaster** [comment]
duplicate of #99?

**Comment by Qwaz** [comment]
Seems so, I was searching with keyword "static" and missed that!
