### ISSUE TITLE
How do I make an error with Box<dyn std::error::Error> 'no_std' compatible?

### ISSUE THREAD

**Issue by pranav-bhatt** [shepmaster/snafu#257]
I couldn't find anything regarding this in the docs. 
I'm trying to make a library `no_std` compatible, however I'm getting stuck in the following lines :
```rust
#[snafu(display("Other error: {:?}", source))]
Other { source: Box<dyn std::error::Error> }
```
Here, I need to replace `std::error:Error` with an appropriate trait. I assume the inbuilt "std::error alternative" would work fine for this, but I don't think I can access it :P 

Any advice on what I could do? Thanks!

**Comment by shepmaster** [comment]
In a `no_std` environment, there is no `Error` trait and there is no `Box` type (or allocation of any kind!), so your goal is not attainable.

I'd recommend _against_ having something like `Other { source: Box<dyn std::error::Error> }`. Instead, I think it's better to have distinct error variants for each unique failure case. By doing that, you get better error messages for your users *and* get no-std compatibility for "free".

**Comment by pranav-bhatt** [comment]
Thank you for the quick response! For now I'm assuming that the environment will support `alloc` (baby steps), hence am allowing myself to use Box for now. As for the `Other { source: Box<dyn std::error::Error> }`, I'll try to weed out the things that depend on it, and make discrete errors. Will keep you updated! But let's say for some reason we require the `Other` error type (mentioned in Spec perhaps), what options do I have then?

Also I'm not sure if I should open another issue, but in spirit of my original title, I guess posting it here makes more sense to me. Since I'm going the no_std route with your library, I'm facing a situation my error sources also need to implement `snafu::Error`. For example, in this case:
```
#[snafu(display("Error while parsing a time string: {}", source))]
    #[snafu(context(false))]
    ParseTimeError { source: chrono::ParseError },
```
I'm getting the following error:
```
No method named `as_error_source` found for reference `&chrono::format::ParseError` in the current scope 

Note: The method `as_error_source` exists but the following trait bounds were not satisfied: chrono::format::ParseError: snafu::Error` which is required by `chrono::format::ParseError: snafu::AsErrorSource`
```
The problem is that I can't implement an external trait for an external library, so I'm stuck here as well 😞
