### ISSUE TITLE
Missing field source

### ISSUE THREAD

**Issue by IsaccBarker** [shepmaster/snafu#264]
Hello! I have been trying to get Snafu to work for close to 3 hours now, and this is my last hope (:
Anyways, I've created the error ProjectError:
```rust
#[derive(Debug, Snafu)]
pub enum ProjectError {
    #[snafu(display("Unable to read configuration from {}", path))]
    IOConfigError {
        #[snafu(source(from(io::Error, Box::new)))]
        source: Box<io::Error>,
        path: &'static str,
    },
}
```

And I'm trying to use it like this:
```rust
fn foo() -> Result<(), ProjectError> {
  let src = fs::read(META_FILE).context(IOConfigError { path: META_FILE })?;
}
```

When I try and compile, I get `missing field 'source' in initializer of 'project::project_error::ProjectError'`. I also got `the trait bound 'project::project_error::ProjectError: snafu::IntoError<_>' is not satisfied`, however, the trait is bound, correct?

Anyways, sorry for the simple question, and thanks in advance.

Also, how do I apply labels? Is this project set so that non-maintainers cannot apply them? Just wondering.

**Comment by IsaccBarker** [comment]
Found a solution. Instead of using `IOConfigError` or `ProjectError::IOConfigError`, you have to use `project_error::IOConfigError` (i.e. not `project_error::ProjectError::IOConfigError`). I may soon submit a pull request for a documentation addition.

**Comment by shepmaster** [comment]
This is the single most confusing part of SNAFU, so more documentation is welcome.

This code:

```rust
#[derive(Debug, Snafu)]
pub enum ProjectError {
    #[snafu(display("Unable to read configuration from {}", path))]
    IOConfigError {
        #[snafu(source(from(io::Error, Box::new)))]
        source: Box<io::Error>,
        path: &'static str,
    },
}
```

expands into (some pieces/details removed):

```
#[derive(Debug, Snafu)]
pub enum ProjectError {
    IOConfigError {
        source: Box<io::Error>,
        path: &'static str,
    },
}

struct IOConfigError {
    source: ...,
    path: ...
}
```

It is this second type that you use as the argument to `context`. More details about the expanstion are [in the guide](https://docs.rs/snafu/0.6.9/snafu/guide/the_macro/index.html).

**Comment by shepmaster** [comment]
> ```rust
>         #[snafu(source(from(io::Error, Box::new)))]
>         source: Box<io::Error>,
> ```

This boxing isn't _required_. You may be doing it for some performance reasons, but it's usually written as:

```rust
        source: io::Error,
```

**Comment by IsaccBarker** [comment]
@shepmaster Cool, thanks! I just submitted a pull request for a quick example on the main page of the docs.
