### ISSUE TITLE
Could not find `convert` in `core` when using `ensure!` with a conflicting module called `core` in scope

### ISSUE THREAD

**Issue by tpdickso** [shepmaster/snafu#270]
```
error[E0433]: failed to resolve: could not find `convert` in `core`
   --> meridian-graphics/src/shader/user_uniform.rs:940:17
    |
940 | /                 ensure!(is_valid_glsl_identifier(name), InvalidUniformBlockFieldIdentifier {
941 | |                     uniform_block_name,
942 | |                     field_name: name
943 | |                 });
    | |___________________^ could not find `convert` in `core`
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
Looks as if the issue is that it considers `core::convert` to be an ambiguous import; writing `use core::convert` in the same source file raises an error that it isn't sure which module to use. Replacing `core::convert` in the `ensure!` macro source with `::core::convert` appears to fix the issue, but I am not sure if that would be a breaking change for another reason.

**Comment by shepmaster** [comment]
Can you provide an example of code that fails? None of my usages or tests cause this error. Perhaps you've defined your own `core` module?

**Comment by shepmaster** [comment]
Please also mention what version of SNAFU you are using. Producing a [MRE](https://github.com/shepmaster/rust-mre) is the fastest way to get help.

**Comment by tpdickso** [comment]
You're right -- I've got a star import from the `nalgebra` crate, which has a `core` module from which it re-exports all of its types at the crate root. Using an absolute import path for `core` would probably make it robust against this interaction. I can put up a PR for that change if it's wanted.

**Comment by shepmaster** [comment]
Most of the time that would be useful, but right now the master branch is in a bit of a state as I'm preparing for the 0.7 release. I'll need to do some branching shenanigans to release a 0.6.10 version, so I can submit a PR soon. I'll tag you with it so you can test.

As a horrible workaround for the next day or two, you can probably import the core crate right before the `ensure!` call.

**Comment by tpdickso** [comment]
Not at my computer at the moment so I can't provide a MRE that actually uses the crate but I can reproduce the error along with the line from the `ensure!` macro source that causes it in the playpen:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=18dc84701dc51c417583b2b4b0d477dc
