### ISSUE TITLE
Auto-context for simple pass-through errors (like `thiserror`)

### ISSUE THREAD

**Issue by hgomersall** [shepmaster/snafu#276]
I've found that `thiserror` and `snafu` fill two distinct roles for me. In the case when I have complex errors that take extra arguments, SNAFU is fantastic. However, in the case when module errors are simple wrappers around library errors, `thiserror` is simpler to use and syntactically tighter. It's also the case that one often gets name collisions with the intermediate structure and the library error, so this doesn't work (which is often frustrating):
```rust
use a_lib::{library_function, LibraryError};

#[derive(Debug, Snafu)]
pub enum MyError {
    #[snafu(display("Error : {}", source))]
    LibraryError { source: LibraryError },
}
fn do_something -> Result<(), MyError>
{
    library_function.context(LibraryError)?;
    Ok(())
}
```
It occurred to me that the SNAFU could fill both roles if in the simple case, the context could be inferred, much like with `thiserror`. Obviously, this depends on being able to disambiguate it, but that would still include many situations.

The solution might even be to include `thiserror` like syntax for pass-through errors:
```rust
use a_lib::{library_function, LibraryError};
use std::io::{self, Write};

#[derive(Debug, Snafu)]
pub enum MyError {
    #[snafu(display("Error : {}", source))]
    LibraryError { #[from] LibraryError },
    #[snafu(display("Error number: {}, source: {}", number, source))]
    AMoreComplicatedError { source: io::Error, number: usize },
}
fn do_something() -> Result<(), MyError>
{
    library_function?;
    io::stdout().write_all(b"hello world").context( AMoreComplicatedError { number: 10 })?;
    Ok(())
}
```

**Comment by hgomersall** [comment]
There's likely a few errors in that code, but I think the point is apparent.

**Comment by shepmaster** [comment]
[You can do that in SNAFU today](https://docs.rs/snafu/0.6.10/snafu/guide/attributes/index.html#controlling-context):

```rust
#[derive(Debug, Snafu)]
pub enum MyError {
    #[snafu(display("Error : {}", source))]
    #[snafu(context(false))] // <--- Here
    LibraryError { source: LibraryError },

    #[snafu(display("Error number: {}, source: {}", number, source))]
    AMoreComplicatedError { source: io::Error, number: usize },
}
```

#199 tracks making this work as `LibraryError(LibraryError)`

**Comment by hgomersall** [comment]
My bad. So `LibraryError(LibraryError)` is currently _not_ supported?

**Comment by hgomersall** [comment]
Also, does it still create the hidden context structs?

Thanks!

**Comment by shepmaster** [comment]
> So `LibraryError(LibraryError)` is currently _not_ supported?

That is correct.

> does it still create the hidden context structs?

It does not.

**Comment by hgomersall** [comment]
Great, thank you!
