### ISSUE TITLE
Allow visibility to be applied to context selectors

### ISSUE THREAD

**Issue by shepmaster** [shepmaster/snafu#28]
My opinion is that error types should be plentiful — each module should have one (or more!) error types. Each error type is only ever constructed by that module (and maybe child modules). Each error type is very tailored to its domain and there are less cases of "but these 31 error variants don't *actually* occur here". This fits really well with SNAFU's default of making context selectors private by default.

However, the concept of a unified error type is present in the Rust ecosystem, and I have found myself wanting to create a child's error for purposes of testing. This would be best served via marking the context selectors with `pub(crate)`. Once we open that can of worms, we can probably allow *any* visibility modifier.

How should we allow users to specify this? My first thoughts are something like this:

```rust
#[derive(Snafu)]
#[snafu::visibility(pub(crate)] // sets the default visibility (uses private if not present)
enum Error {
    Alpha,
    #[snafu::visibility(pub)] // sets the specific visibility (uses the default if not present)
    Beta,
}
```

**Comment by shepmaster** [comment]
I have a [partially-implemented branch](https://github.com/shepmaster/snafu/compare/visibility?expand=1) where I quickly hacked up the default to be `pub(crate)` — if you are experiencing issues, you can try that and see if it helps your case.

**Comment by mikeando** [comment]
I think this solution will work for me. 

I initially wondered about the multiple `#[snafu::xyz]` bits that could be added to each entry, 
and whether they should be combined into a single attribute. i.e. instead of

```
#[derive(Snafu)]
enum Error {
    #[snafu::visibility(pub)]
    #[snafu::description("a:{}", "source")]
    A{source: io::Error},
    ...
}
```

it could be something like

```
#[derive(Snafu)]
enum Error {
    #[snafu(visibility=pub, description=("a:{}","source")]
    A{source: io::Error}
```

But thinking deeper about it - the slightly more verbose first version may be better handled by source control, so I think it is better.
