### ISSUE TITLE
Allow conversion from unit error values

### ISSUE THREAD

**Issue by kesmit13** [shepmaster/snafu#281]
Some methods such as `set_port` on `url::URL` return `Err(())`. I'd like to be able to convert that to my own error type and add a message, but I haven't figured out if that's possible. The following syntax doesn't work. Is there a way to handle this?
```
#[derive(Debug, Snafu)]
pub enum Error {
    #[snafu(display("{}", message))]
    Unknown {
        message: String,
        source: (),
    }
}
```

**Comment by shepmaster** [comment]
You should be able to do something like

```rust
#[derive(Debug, Snafu)]
pub enum Error {
    #[snafu(display("{}", message))]
    Unknown {
        message: String,
    }
}

url.set_port(...).map_err(|_| Unknown { string: "whatever" }.build())?;
```

See also:

- #214
- #103 
- #23

Please feel free to close this is that resolves your problem!

**Comment by kesmit13** [comment]
That's basically what I'm doing now. I was just hoping there was something a bit more consistent like:
```
url.set_port(...).context(Unknown( message: "..." })?;
```

**Comment by shepmaster** [comment]
That's the point of #103 and #23, yes.

**Comment by kesmit13** [comment]
#23 seems like a more general statement of the issue that I'm seeing here.
