### ISSUE TITLE
Need a way to incorporate i18n behaviors in display

### ISSUE THREAD

**Issue by kesmit13** [shepmaster/snafu#283]
The `display(...)` directive in snafu accepts a particular format of string for doing formatted substitutions. Is there a way to incorporate translated strings in this? Having a way to integrate with something like [fluent](https://docs.rs/fluent/0.15.0/fluent/index.html) where the substitution variable map could be generated automatically would be ideal. Maybe there is a way to override the display method in snafu that I just haven't seen yet.

**Comment by shepmaster** [comment]
See also https://github.com/projectfluent/fluent-rs/issues/107

**Comment by kesmit13** [comment]
Yep, that's almost exactly what I was thinking.

**Comment by shepmaster** [comment]
Closing as duplicate of #254

**Comment by kesmit13** [comment]
So is there any way to currently use something other than a string literal as an error message?

**Comment by shepmaster** [comment]
There is not.
