### ISSUE TITLE
Issues with IntelliJ integration

### ISSUE THREAD

**Issue by kesmit13** [shepmaster/snafu#288]
I've noticed a couple of issues with Snafu and IntelliJ not getting along. I was just curious if there were any workarounds you were aware of. First, IntelliJ doesn't seem to recognize that Snafu errors have the Display trait implement. When you try to use them in an `eprintln!` they show up as an error in the editor. Second, IntelliJ doesn't recognize the generated error structs. They show up as "Unresolved reference"s.

**Comment by shepmaster** [comment]
I do not use IntelliJ, sorry.

>  IntelliJ doesn't seem to recognize that Snafu errors have the Display trait implement.

That's surprising, as that shouldn't be any different from other `derive` macros. Does it support other derive macros like serde's `Serialize` / `Deserialize`?

> IntelliJ doesn't recognize the generated error structs

I do know that rust-analyzer (needed / still needs?) configuration options to best work with SNAFU:

```elisp
  (lsp-rust-analyzer-cargo-load-out-dirs-from-check t)
  (lsp-rust-analyzer-proc-macro-enable t)
```

If IntelliJ has any similar configuration options, I'd check that out.

**Comment by kesmit13** [comment]
This is the first time I've seen IntelliJ not recognize a trait on something. I'll investigate on my own. I just thought I'd open an issue to see if anyone else had seen the same things.
