### ISSUE TITLE
Customize `Location` debug output to remove `_other`

### ISSUE THREAD

**Issue by shepmaster** [shepmaster/snafu#333]
It's noise and looking at the `Debug` format is pretty common for quick debugging.

**Comment by hellow554** [comment]
What about using `#[non_exhaustive]` instead of `_other`? See https://stackoverflow.com/a/70965787/1021920 for more information 😜

**Comment by Enet4** [comment]
The [code itself](https://github.com/shepmaster/snafu/blob/main/src/lib.rs#L1289) seems to have that hint, but the current minimum tested version of Rust is 1.34. Unless we're OK with bumping this in the next version, we'll need to gate the presence 
of `_other` on a feature ([rust_1_46](https://docs.rs/snafu/0.7.1/snafu/guide/compatibility/index.html#rust_1_46) already exists) or just keep it regardless.

**Comment by hellow554** [comment]
> current minimum tested version of Rust is 1.34

Where do you get that information from? I can't find that in the readme or docs?

`#[non_exhaustive]` was introduced in 1.40 so `rust_1_46` should be okay to use, I guess?
Else one could use a `build.rs` file to determine the rust version and detect the rust version which then sets the feature flag automatically.

In the end, it should be relativly easy to adapt the `Debug` output, by using [`debug_struct`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.debug_struct) even without using `#[non_exhaustive]`:

```rust
fmt.debug_struct("Location")
            .field("file", &self.file)
            .field("line", &self.line)
            .field("column", &self.column)
            .finish()
```

(btw. hello enet4 👋 :) )
