### ISSUE TITLE
snafu-derive syn is still in v1.0 

### ISSUE THREAD

**Issue by Enet4** [shepmaster/snafu#379]
A major version of syn (v2.0) was released a while ago. In my projects, all other syn dependents but snafu have done the jump. Would you be interested in a PR to migrate syn to version 2?

**Comment by shepmaster** [comment]
Yeah, I've been eyeing that. The "problem" is that it also comes with a MSRV bump, which means SNAFU will have to have a MSRV bump and thus bump the minor version. Bumping the MSRV should also involve checking and cleaning things like the `rust_1_39` and `rust_1_46` features. It would also allow us to finally move to edition 2021. 

Rust 1.56 was 2021-10-21, so hopefully people will have been able to upgrade by now.

Have you tried bumping the syn version / any ideas what kind of changes are needed?

**Comment by 8573** [comment]
As a point of reference, Debian has Rust 1.63 in its stable release, 1.48 in "oldstable", and 1.41 in "oldoldstable" (long-term support out to [2024-06-30](https://wiki.debian.org/DebianReleases)).  Alpine Linux 3.15 and newer have Rust 1.56 and newer; Alpine 3.10, the oldest [not-completely-unsupported](https://alpinelinux.org/releases/) version covered by the [package catalog](https://pkgs.alpinelinux.org/packages?name=rust&branch=v3.10&repo=&arch=&maintainer=), has Rust 1.34. I'm not sure any other distro both packages Rust and is conservative in updating it similarly to Debian; Debian at least is the most famous. (I've checked Fedora, Ubuntu, OpenSUSE, Arch, Gentoo, NixOS, Guix.)

**Comment by Enet4** [comment]
> Have you tried bumping the syn version / any ideas what kind of changes are needed?

Just gave it a try. The trickiest part was adjusting the `DocComment` definition to comply with the way that attributes are parsed in the new version (it's hard for me to explain why), the rest was renaming a type and changing a field access to a method call.

A good deal of the code changes would still be around requiring Rust 1.56, mostly to clean up conditional attributes and removing outdated content.
I pushed them all into [this branch](https://github.com/shepmaster/snafu/compare/main...Enet4:snafu:change/syn_2) which I hope do both of these well. Let me know if you would be willing to consider a PR with this.

**Comment by shepmaster** [comment]
Sure, feel free to open that as a PR where we can iterate and comment. 

<details>
<summary>Comments I would have left and we can discuss on the PR</summary>

- It'll be fine to have this as separate PRs (e.g. upgrade syn, bump MSRV). The latter probably would need be committed first, but may be easier to be driven by the former. `git rebase` to the rescue!
- We probably need to grep for (variations on) 1.34 / 1.39 / 1.46 to find places we talk about them in prose.
- Why did snafu-derive get a `default = []` feature?
- The `yes_async::async_body` module can probably be inlined.
- `fn track_caller()` can probably be inlined as well
- Nice catch on the `non_exhaustive` note

</details>

**Comment by 8573** [comment]
I'd like to say that I, supporting generous MSRVs, appreciate SNAFU's current generosity in its MSRV, but I, getting it for free, don't ask that that generosity be in any way permanent, particularly if it's incurring the cost in time-to-compile of an otherwise unnecessary and not small dependency.
