### ISSUE TITLE
Use the same deprecation macros on the no_std Error as the official Error

### ISSUE THREAD

**Issue by NWPlayer123** [shepmaster/snafu#425]
While writing up documentation, I noticed several deprecation warnings concerning description and cause, which have been deprecated since March 2020 and February 2019 respectively, which are coming up on 4 and 5 years ago, so I think it's high time to remove them entirely. Any repositories that still rely on it can either fix to a specific older version, or update their code to remove it.

**Comment by NWPlayer123** [comment]
So it does, interesting. I was mostly bringing this up because I found https://github.com/shepmaster/snafu/blob/main/src/no_std_error.rs#L6 as I was digging around how no_std works, and that's what I was mostly taking issue with.

In that case, you should use the same deprecation macro as the official Error does, as library authors are able to use it.
![image](https://github.com/shepmaster/snafu/assets/3280345/ef95ed95-0cc5-4ede-a32f-1c8a672648c3)

**Comment by shepmaster** [comment]
> around how no_std works

If possible for your case, I'd recommend that you use the [unstable-core-error](https://docs.rs/snafu/latest/snafu/guide/feature_flags/index.html#unstable-core-error) feature flag to use the version of `Error` that lives in the core library. Once that is stable enough, SNAFU will no longer have a reason to create its own `Error` trait.
