### ISSUE TITLE
`Report` print doesn't prefix with "Error: "

### ISSUE THREAD

**Issue by DerickEddington** [shepmaster/snafu#452]
In `src/report.md`, it says the example's printed output will be prefixed with "Error: " [[1]](https://github.com/shepmaster/snafu/blob/117aeeea7699922d807ba0f897d494e13b84fb7a/src/report.md?plain=1#L64):
```console
Error: Unable to frobnicate the mumbletypeg
[...]
```

But when the example, or any other program using `Report` as the return type of the `main` function, is actually run, its output is not prefixed like that, and its actual output is like:
```console
Unable to frobnicate the mumbletypeg
[...]
```
 
I'm guessing the original intention was for this to print the "Error: " prefix, because `src/report.md` saying that it will is part of the same commit where the actual formatting was introduced [[2]](https://github.com/shepmaster/snafu/commit/acac2d56ad07eb51e3fec406d392c4beecff8cf5).

I'd prefer if this did print the prefix, because I rely on that to more easily notice when there was an error (vs. non-error printed output), and because that would be more consistent with the `std` library's printing [[3]](https://github.com/rust-lang/rust/blob/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/process.rs#L2443) and with other error-helping libraries IIRC. 

Maybe fixing this is as simple as:
```diff
--- a/src/report.rs
+++ b/src/report.rs
@@ -188,7 +188,7 @@ where
         match self.0 {
             Ok(()) => ExitCode::SUCCESS,
             Err(e) => {
-                eprintln!("{}", ReportFormatter(&e));
+                eprintln!("Error: {}", ReportFormatter(&e));
 
                 #[cfg(feature = "unstable-provider-api")]
                 {
```

**Comment by shepmaster** [comment]
The problem arises from the fact that we support older versions of Rust:

```toml
[dependencies]
snafu = { version = "0.8.2", default-features = false }
```

```rust
use snafu::prelude::*;

#[snafu::report]
fn main() -> Result<(), Error> {
    Err(Error)
}

#[derive(Debug, Snafu)]
struct Error;
```

```
% cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/whawha`
Error: Error
```

When targeting older versions of Rust, we transform `main` into

```rust
fn main() -> Result<(), Report<Error>>
```

When targeting newer versions:

```rust
fn main() -> Report<Error>
```

As you said, the standard library is the one that adds the `Error:` prefix when printing out the `Result`.

---

Your fix seems like the right direction, we just need to ensure that we don't end up printing `Error: Error: ...` when older versions of Rust are targeted.
