### ISSUE TITLE
Raw identifier not supported in the `display` attribute

### ISSUE THREAD

**Issue by hellow554** [shepmaster/snafu#60]
Using snafu version 0.2.3 does not support [raw identifiers](https://doc.rust-lang.org/stable/rust-by-example/compatibility/raw_identifiers.html) (e.g. `r#type`).

This does not work currently:
```rust
use snafu::Snafu;

#[derive(Debug, Snafu)]
enum Error {
    #[snafu(display("{}", r#type))]
    Oc { r#type: String }
}
```

```
cargo build
   Compiling proc-macro2 v0.4.28
   Compiling libc v0.2.51
   Compiling cc v1.0.35
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.32
   Compiling autocfg v0.1.2
   Compiling cfg-if v0.1.7
   Compiling rustc-demangle v0.1.14
   Compiling backtrace v0.3.15
   Compiling backtrace-sys v0.1.28
   Compiling quote v0.6.12
   Compiling snafu-derive v0.2.3
   Compiling snafu v0.2.3
   Compiling foo v0.1.0 (/tmp/tmp.mSGf3U1WvR/foo)
error: expected expression

error: aborting due to previous error

error: Could not compile `foo`.
```

**Comment by hellow554** [comment]
I also would suggest to improve the error message in this case, because I have no clue what's going on under the hood ^^

**Comment by shepmaster** [comment]
The problem is that the arguments to `#[snafu(display)]` are expected to be a comma-separated list of expressions, but it appears that `r#type` isn't considered one...

**Comment by hellow554** [comment]
"Found ini the field" might not be correct @shepmaster . It's more that I know a lot of proc macros stumble across that, e.g. https://github.com/SergioBenitez/Rocket/issues/881

**Comment by shepmaster** [comment]
I've filed https://github.com/dtolnay/syn/issues/628 as I don't *think* this is my fault. In the meantime, try this workaround:

```rust
#[snafu(display = r#"("{}", r#type)"#)]
Oc { r#type: String }
```

**Comment by shepmaster** [comment]
> improve the error message in this case,

This would be difficult as the error message comes directly from syn.

**Comment by dtolnay** [comment]
Both the fact that it doesn't work as written, and that the error message is rendered without a source line of code, are compiler bugs. The error message should be getting placed as:

```console
error: expected expression
 --> src/main.rs:5:27
  |
5 |     #[snafu(display("{}", r#type))]
  |                           ^^^^^^
```

The root cause for both is https://github.com/rust-lang/rust/issues/43081.

**Comment by hellow554** [comment]
Hey @shepmaster,

rocket solved the issue in https://github.com/SergioBenitez/Rocket/commit/97f6bc5dc0c842609bf92a106a78844c8e346fdd maybe it is something snafu can adopt?

**Comment by shepmaster** [comment]
This may have magically fixed itself in the intermediate time:

```
% cat examples/raw.rs
use snafu::Snafu;

#[derive(Debug, Snafu)]
enum Error {
    #[snafu(display("{}", r#type))]
    Oc { r#type: String }
}

fn main() {}

% cargo build --example=raw
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
```
