### ISSUE TITLE
From implementations for converting from source error types

### ISSUE THREAD

**Issue by jturner314** [shepmaster/snafu#78]
I'm evaluating `snafu` as a replacement for `quick-error` and came across a couple of ergonomic issues that I thought would be worth mentioning. They are both related to implementing `From` such that the error variant is determined by the source error type.

## Without context

First, let's consider the case where you want a variant that acts as a wrapper for a source error type with no additional context. For example, let's say you want an error type

```rust
pub enum MyError {
    Foo(FooError),
    Bar(BarError),
}
```

This represents an error that is created from either a source error of type `FooError` or a source error of type `BarError` with no additional context information. `quick-error` handles this nicer than `snafu` in two ways:

1. It allows using a tuple variant (`Foo(FooError)`) instead of requiring a struct variant (`Foo { source: FooError }`).

2. It makes it easy to create `impl From<FooError> for MyError` and `impl From<BarError> for MyError`. (`quick-error` makes this easy by having the user write `from()` to specify that they want a `From` implementation to be created.)

   This makes it possible to write

   ```rust
   // using quick-error
   fn my_fn() -> Result<(), MyError> {
       returns_result_with_foo_error()?;
       Ok(())
   }
   ```

   instead of having to explicitly specify the variant with

   ```rust
   // using snafu
   fn my_fn() -> Result<(), MyError> {
       returns_result_with_foo_error().context(Foo)?;
       Ok(())
   }
   ```

Item 1 isn't critical, but it would be nice to have. (It looks like discussion about this is in #61, so I won't talk about it more here.)

Item 2 is pretty important so that `?` works without having to call `.context()`. I suppose you could argue that the user should always call `.context()` to explicitly specify the error variant, but when the variant can be determined directly from the source error type, IMO calling `.context()` is unnecessarily verbose.

## With context

A related issue is when the error variant does have context information but the error variant can still be determined from the source error type. For example,

```rust
pub enum MyError {
    Foo {
        message: String,
        source: FooError,
    },
    Bar {
        message: String,
        source: BarError,
    },
}
```

Similar to the case without context, it would be nice to be able to use the `?` operator without explicitly specifying the error variant. So, it would be nice to be able to write

```rust
// using quick-error
fn my_fn() -> Result<(), MyError> {
    returns_result_with_foo_error().context("message")?;
    Ok(())
}
```

instead of

```rust
// using snafu
fn my_fn() -> Result<(), MyError> {
    returns_result_with_foo_error().context(Foo { message: "message"})?;
    Ok(())
}
```

To do this, we need an easy way to create `impl<C: Into<String>> From<Context<FooError, C>> for MyError` (or just `impl<'a> From<Context<FooError, &'a str>> for MyError`).

`quick-error` makes this easy by allowing the user to write `context(message: &'a str, source: FooError) -> (message.to_string(), source)` to specify that they want a `From<Context<&'a str, FooError>>` implementation to be created [note: `quick-error` swaps the type parameters of `Context`].

Edit: By the way, I wanted to mention that your documentation is awesome!

**Comment by shepmaster** [comment]
Thank you for the feedback and kind words! I've some questions about some of your points to better understand the goals, but to be transparent, I'm starting from a "mildly disinclined to make the related changes" position. I don't mean to say that the ideas are bad, just that they might not fit with SNAFU's philosophy.

One thing that I will point out to start with is that the error and context selector types are "normal" Rust types, so you can write unsupported code yourself:

```rust
#[derive(Debug, Snafu)]
enum Error {
    // ...
}

impl From<Whatever> for Error {
    fn from(other: Whatever) -> Self { /* ... */ }
}
```

Obviously this isn't ideal for patterns that we *want* to be common in SNAFU.

> you want a variant that acts as a wrapper for a source error type with no additional context.

Could you provide some concrete examples from your code where this arises? That will help us understand the patterns in play.

Ultimately, I feel this is my big sticking point. I want SNAFU to encourage people to put more detail into their errors for the benefit of downstream consumers. Using a tuple variant makes providing context harder. Not providing *any* context makes the information less rich.

> `?` works without having to call `.context()`

I think this would be straightforward. For any variant that doesn't have user-provided info, we can implement `From`. If there are multiple overlapping implementations (due to the source *not* being unique), the user will just get a trait error when they attempt to use it.

> when the error variant does have context information but the error variant can still be determined from the source error type

This *might* be possible do do with [the recent (unreleased!) changes to how `context` works](https://github.com/shepmaster/snafu/commit/82085e745f07feb6f82fb33917d103d1da95740e). I'd have to play with it to see.

However, the proposed syntax has a *really* sharp cliff:

```rust
returns_result_with_foo_error().context("message")?;
```

This falls apart as soon as you have more than one piece of information; there's no way to pass two arguments. You'd have to fall back to a tuple (which has the downsides as linked in the other issue):

```rust
returns_result_with_foo_error().context(("message", "another"))?;
```

Or force upgrading to a struct-like variant.

> instead of
> 
> ```rust
> returns_result_with_foo_error().context(Foo { message: "message"})?;
> ```

I know that you are using example code here, but it'd be rare to use a literal like this — those would normally just be another variant. Otherwise, `message` would likely be a variable, reducing syntactic overhead:

```rust
returns_result_with_foo_error().context(Foo { message })?;
```

**Comment by jturner314** [comment]
> One thing that I will point out to start with is that the error and context selector types are "normal" Rust types, so you can write unsupported code yourself:

Right, and simply telling the user to write the necessary `From` impls themselves is certainly a valid position. In fact, I wouldn't recommend providing any of these `From` impls by default due to the "multiple variants corresponding to a single source error type" issue you mentioned. I'd suggest having the user specify that they want a `From` impl to be created by adding an annotation to the appropriate variant (similar to how `quick-error` requires the user to specify `from()`, `from(TheErrorType)`, etc. This would also avoid the "multiple variants for a single source error type" issue since the compiler doesn't allow overlapping impls, so the user would get a compilation error if they tried creating two `From` implementations for the same source error type.

### Without context

> > you want a variant that acts as a wrapper for a source error type with no additional context.
> 
> Could you provide some concrete examples from your code where this arises? That will help us understand the patterns in play.
> 
> Ultimately, I feel this is my big sticking point. I want SNAFU to encourage people to put more detail into their errors for the benefit of downstream consumers. Using a tuple variant makes providing context harder. Not providing _any_ context makes the information less rich.

`snafu` encourages users to create many small error enums (e.g. one per module). When I do this, what happens is that many variants of higher-level error enums are just thin wrappers around the lower-level error enums. Some good examples of this are the error types from the [`ndarray-npy`](https://docs.rs/ndarray-npy/0.4.0/ndarray_npy/) crate. Let's consider the error types associated with reading a file in the `.npz` format. (The `.npz` format is a zipped archive of files in `.npy` format. Each `.npy` file represents an n-dimensional array and has a header (which specifies the format version number and a Python dictionary literal with some metadata) and the array's binary data.)

* The top-level error type is [`ReadNpzError`](https://docs.rs/ndarray-npy/0.4.0/ndarray_npy/enum.ReadNpzError.html), which is used by the [`NpzReader`](https://docs.rs/ndarray-npy/0.4.0/ndarray_npy/struct.NpzReader.html) struct. There are two error variants that are used: one for errors reading the zip archive and one for errors parsing the inner `.npy` files. [There's also an `Io` variant, but that variant actually needs to be removed because it's never used.] Each of these variants is a thin wrapper around its respective source error, because there really isn't much context to add. For the `Npy` variant, I suppose I could add the name/index of the file within the archive trying to be read, but IMO the caller should handle that, not `ReadNpzError`, since the caller has that information anyway (analogous to how `std::io::Error` doesn't include the file path).

* For the `Npy` variant of `ReadNpzError`, the corresponding error type is [`ReadNpyError`](https://docs.rs/ndarray-npy/0.4.0/ndarray_npy/enum.ReadNpyError.html), which is used by the [`ReadNpyExt`](https://docs.rs/ndarray-npy/0.4.0/ndarray_npy/trait.ReadNpyExt.html) trait (which is called by the implementations of the `NpzReader` methods). `ReadNpyError` has quite a few variants, including a few that don't have a source error type and a few that do. For example, the `HeaderParse` variant is a thin wrapper around `HeaderParseError`. There really isn't much context to add to that variant; it's just an error related to parsing the file's header.

* The [`HeaderParseError`](https://github.com/jturner314/ndarray-npy/blob/4d659248cd5ab122d914d5b0601df3d1d9f09022/src/npy/header.rs#L12-L55) enum is private for the time being, although I may expose it in the public API in the future. It has quite a few variants including some without any additional information, some with context information, and a couple corresponding to specific source error types (`NonAscii` and `DictParse`). I could make `NonAscii` a thin wrapper around [`std::str::Utf8Error`](https://doc.rust-lang.org/std/str/struct.Utf8Error.html), but for the time being, it doesn't include that information. The `DictParse` variant is a thin wrapper around [`PyValueParseError`](https://docs.rs/py_literal/0.2.0/py_literal/enum.ParseError.html), and there really isn't any additional context information to add here. (There's a single Python dictionary literal in the file header, and this error variant corresponds to a failure parsing that dictionary.)

So, there are a number of error variants that correspond to a single source error type and need no additional context information. I think that this will be especially common when creating lots of small error types as `snafu` encourages. For these cases, it's nice to have an `impl From<TheSourceError> for ErrorWrapperEnum` so that the `?` operator works without `.context()`.

### With context

> However, the proposed syntax has a _really_ sharp cliff:
> 
> ```rust
> returns_result_with_foo_error().context("message")?;
> ```
> 
> This falls apart as soon as you have more than one piece of information; there's no way to pass two arguments. You'd have to fall back to a tuple (which has the downsides as linked in the other issue):

Yeah, that's a good point I didn't consider.

My use-case for this is in another crate (unfortunately non-public for the time being). Basically, I have some large methods that are performing quite a few linear algebra operations, and many of the linear algebra operations (e.g. matrix inversions, factorizations, etc.) can fail for various reasons. All of the linear algebra errors have the same source error type, [`LinalgError`](https://docs.rs/ndarray-linalg/0.10.0/ndarray_linalg/error/enum.LinalgError.html), so I want to provide some context information to identify the location of the linear algebra operation that caused the error for debugging purposes. Since I'm performing so many linear algebra operations, there are so many possibilities that I've taken the lazy way out and just added a `String` of context (which is created from a string literal).

In retrospect, it would probably be simpler to just add a backtrace to the `Linalg` variant of my error type instead of a bunch of `.context("string literal message")?` in the source code. Is there a performance cost to using backtraces in error types?

**Comment by shepmaster** [comment]
Thanks for the well-stated arguments for your positions!

---

What's rough about

> I wouldn't recommend providing any of these `From` impls by default

is:

> I think that this will be especially common when creating lots of small error types as `snafu` encourages

It's unfortunate that the *encouraged* design would require more ceremony. 

SNAFU could automatically implement `From<SourceError> for Error` if we detect that the `SourceError` is unique in this enum and there are no user fields. I see two downsides to this path:

1. When the source error is no longer unique or user fields are added, previously working code will fail with a missing trait error.
1. Sometimes we won't be able to detect this properly and will require an opt-out mechanism.
  - Recursive error types (as it will conflict with the blanket of `impl From<T> for T`).
  - If someone uses a unique type alias for a source error type (this seems silly).
  - Some complicated generic type shenanigans, I'm sure.

Do you have any suggested syntax for what you'd want an attribute to look like? 

```rust
#[derive(Debug, Snafu)]
#[snafu(...)] // Should there be an apply to all variants version?
enum Error {
    #[snafu(...)]
    Alpha { source: TypeOne },
    #[snafu(...)] // Is there a negated version to opt-back out?
    Beta { source: TypeTwo },
}
```

> what happens is that many variants of higher-level error enums are just thin wrappers around the lower-level error enums

Does that mean that there's generally only one narrow entrypoint to each module? That's the primary way I can see there being no context for an error: there's only one function in the parent module that generates the child module's error.

> I've taken the lazy way out

You *may* be interested in the ["strings as errors" pattern](https://docs.rs/snafu/0.3.1/snafu/guide/comparison/failure/index.html#strings-as-errors) from failure. You could create a macro for this specific error variant (among other, richer variants), potentially using the `file`/`line`/`column` macros or adding a `Backtrace`.

> Is there a performance cost to using backtraces in error types? Does the cost only occur when the backtrace is created, or is there an ongoing cost to having backtraces enabled?

The cost should only be when the error occurs and the backtrace is created, although I've just opened #84 to improve the performance impacts.

**Comment by shepmaster** [comment]
If anyone is interested in reviewing an implementation of this, there’s an [in-progress version available](https://github.com/shepmaster/snafu/tree/from-no-context). It looks like:

```rust
use snafu::Snafu;

#[derive(Debug, Snafu)]
enum Error {
    #[snafu(context(false))]
    NeedsNoIntroduction { source: VeryUniqueError },
}

fn my_code() -> Result<i32, Error> {
    let val = do_something_unique()?;
    Ok(val + 10)
}

#[derive(Debug, Snafu)]
enum VeryUniqueError {}

fn do_something_unique() -> Result<i32, VeryUniqueError> {
    Ok(42)
}
```

**Comment by vojtechkral** [comment]
So I'm not sure whether this has been considered, but could newtypes be used to make both with-context and without-context errors easier to work with?

Ie. with context:

```Rust
enum Error {
    #[snafu(display("Could not open config from {}: {}", 0.display(), 1))]
    OpenConfig(PathBuf, Source(std::io::Error)),

    // ...
},
```

Without context:

```Rust
enum Error {
    OpenConfig(Source(std::io::Error)),

    // ...
},
```

Related: #61 . The benefit for with-context cases would be that they would be easier to construct. This might in fact be useful for struct-variant cases too, you could mark sources/backtraces with just the newtype rather than an annotation.

**Comment by 0xpr03** [comment]
Just wanted to leave at least a note:
I'm now also rolling the From-Convert code found in the other issue. Because in my use case this way it'll make sense for me.
I can't say provide much context when my 24/7 Connection-Pool to the DB throws errors, this will mean 99,9% that the DB is down or my SQL broken and I should feel bad :P
```
impl std::convert::From<mysql::Error> for DBError {
    fn from(e: mysql::Error) -> Self {
        DBError::Mysql { source: e }
    }
}
```
